name: Jacoco with Java Gradle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  jacoco-java-gradle:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Run Tests
      run: ./gradlew test

    - name: Run Test Coverage
      run: ./gradlew jacocoTestReport

    - name: Generate JaCoCo Badge
      uses: cicirello/jacoco-badge-generator@v2
      with:
        generate-branches-badge: true
        jacoco-csv-file: build/customJacocoReportDir/test/jacocoTestReport.csv
        
    - name: Update Jacoco Badge
      uses: test-room-7/action-update-file@v1
      with:
        file-path: .github/badges/jacoco.svg
        commit-msg:  Update Jacoco Badge
        github-token: ${{ secrets.GITHUB_TOKEN }}
